export const MALAWI_DISTRICTS = [
  "Balaka",
  "Blantyre",
  "Chikwawa",
  "Chiradzulu",
  "Chitipa",
  "Dedza",
  "Dowa",
  "Karonga",
  "Kasungu",
  "Likoma",
  "Lilongwe",
  "Machinga",
  "Mangochi",
  "Mchinji",
  "Mulanje",
  "Mwanza",
  "Mzimba",
  "Neno",
  "Nkhata Bay",
  "Nkhotakota",
  "Nsanje",
  "Ntcheu",
  "Ntchisi",
  "Phalombe",
  "Rumphi",
  "Salima",
  "Thyolo",
  "Zomba",
] as const;

export const MALAWI_PUBLIC_UNIVERSITIES = [
  "Kamuzu University of Health Sciences (KUHeS)",
  "Lilongwe University of Agriculture and Natural Resources (LUANAR)",
  "Malawi University of Business and Applied Sciences (MUBAS)",
  "Malawi University of Science and Technology (MUST)",
  "Mzuzu University (MZUNI)",
  "University of Malawi (UNIMA)",
] as const;
